# Generated by Django 4.2.1 on 2023-11-27 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('priority', models.TextField(blank=True, default='', null=True)),
                ('createTask', models.DateField(auto_now_add=True)),
                ('endTask', models.DateField(auto_now_add=True)),
                ('UploadFile', models.FileField(null=True, upload_to='')),
                ('Assignee', models.TextField(blank=True, default='', null=True)),
                ('projects', models.CharField(choices=[('ANDELA', 'andela'), ('TEK-EXPERTS', 'tek-experts'), ('UDEMY', 'udemy')], default='', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
