# Generated by Django 4.2.1 on 2023-11-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0002_remove_task_user_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(blank=True, choices=[('LOW', 'low'), ('NORMAL', 'normal'), ('HIGH', 'high')], default='', null=True),
        ),
    ]
